services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: eventostec
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata: